# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1247, 773)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_11 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_11.setMargin(1)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.East)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setMargin(6)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.left_frame = QtGui.QFrame(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_frame.sizePolicy().hasHeightForWidth())
        self.left_frame.setSizePolicy(sizePolicy)
        self.left_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.left_frame.setFrameShadow(QtGui.QFrame.Plain)
        self.left_frame.setObjectName(_fromUtf8("left_frame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.left_frame)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.frame_6 = QtGui.QFrame(self.left_frame)
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_6.setMargin(5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.sensor_container = QtGui.QGridLayout()
        self.sensor_container.setObjectName(_fromUtf8("sensor_container"))
        self.gridLayout_6.addLayout(self.sensor_container, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_6, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.left_frame, 0, 0, 1, 1)
        self.right_frame = QtGui.QFrame(self.tab)
        self.right_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.right_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.right_frame.setObjectName(_fromUtf8("right_frame"))
        self.gridLayout = QtGui.QGridLayout(self.right_frame)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.right_frame)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame)
        self.gridLayout_7.setMargin(5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.camera_container = QtGui.QGridLayout()
        self.camera_container.setObjectName(_fromUtf8("camera_container"))
        self.gridLayout_7.addLayout(self.camera_container, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 4)
        self.frame_2 = QtGui.QFrame(self.right_frame)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_8.setMargin(5)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.joystick_container = QtGui.QGridLayout()
        self.joystick_container.setObjectName(_fromUtf8("joystick_container"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.joystick_container.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.joystick_container, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 1, 1, 1, 1)
        self.frame_4 = QtGui.QFrame(self.right_frame)
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_10.setMargin(5)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.reading_container = QtGui.QGridLayout()
        self.reading_container.setContentsMargins(0, -1, 0, -1)
        self.reading_container.setObjectName(_fromUtf8("reading_container"))
        self.label_9 = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setTextFormat(QtCore.Qt.LogText)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.reading_container.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.reading_container, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_4, 1, 0, 2, 1)
        self.frame_3 = QtGui.QFrame(self.right_frame)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_9.setMargin(5)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.list_container = QtGui.QHBoxLayout()
        self.list_container.setObjectName(_fromUtf8("list_container"))
        self.gridLayout_9.addLayout(self.list_container, 1, 0, 1, 1)
        self.map_container = QtGui.QVBoxLayout()
        self.map_container.setObjectName(_fromUtf8("map_container"))
        self.gridLayout_9.addLayout(self.map_container, 0, 0, 1, 1)
        self.gridLayout_9.setRowStretch(0, 3)
        self.gridLayout_9.setRowStretch(1, 1)
        self.gridLayout.addWidget(self.frame_3, 1, 2, 2, 2)
        self.frame_5 = QtGui.QFrame(self.right_frame)
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_5.setMargin(5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.stop_container = QtGui.QGridLayout()
        self.stop_container.setObjectName(_fromUtf8("stop_container"))
        self.gridLayout_5.addLayout(self.stop_container, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_5, 2, 1, 1, 1)
        self.gridLayout.setRowStretch(0, 4)
        self.gridLayout.setRowStretch(1, 4)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout_2.addWidget(self.right_frame, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 6)
        self.gridLayout_2.setColumnStretch(1, 48)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayout = QtGui.QFormLayout(self.tab_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(300, -1, 300, -1)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_5.setLineWidth(1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.map_val = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_val.sizePolicy().hasHeightForWidth())
        self.map_val.setSizePolicy(sizePolicy)
        self.map_val.setMaxLength(100)
        self.map_val.setObjectName(_fromUtf8("map_val"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.map_val)
        self.label_2 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.cam1 = QtGui.QComboBox(self.tab_2)
        self.cam1.setObjectName(_fromUtf8("cam1"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cam1)
        self.label_3 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_3)
        self.cam2 = QtGui.QComboBox(self.tab_2)
        self.cam2.setObjectName(_fromUtf8("cam2"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.cam2)
        self.label_4 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_4)
        self.cam3 = QtGui.QComboBox(self.tab_2)
        self.cam3.setObjectName(_fromUtf8("cam3"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.cam3)
        spacerItem = QtGui.QSpacerItem(618, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtGui.QFormLayout.SpanningRole, spacerItem)
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 7, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 8, 0, 1, 1)
        self.tile_16_label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tile_16_label.setFont(font)
        self.tile_16_label.setText(_fromUtf8(""))
        self.tile_16_label.setObjectName(_fromUtf8("tile_16_label"))
        self.gridLayout_3.addWidget(self.tile_16_label, 9, 2, 1, 1)
        self.api_select = QtGui.QComboBox(self.groupBox)
        self.api_select.setObjectName(_fromUtf8("api_select"))
        self.api_select.addItem(_fromUtf8(""))
        self.api_select.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.api_select, 6, 1, 1, 2)
        self.tile_18 = QtGui.QLineEdit(self.groupBox)
        self.tile_18.setToolTip(_fromUtf8(""))
        self.tile_18.setObjectName(_fromUtf8("tile_18"))
        self.gridLayout_3.addWidget(self.tile_18, 11, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 11, 0, 1, 1)
        self.tile_18_label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tile_18_label.setFont(font)
        self.tile_18_label.setText(_fromUtf8(""))
        self.tile_18_label.setObjectName(_fromUtf8("tile_18_label"))
        self.gridLayout_3.addWidget(self.tile_18_label, 11, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 10, 0, 1, 1)
        self.tile_17 = QtGui.QLineEdit(self.groupBox)
        self.tile_17.setToolTip(_fromUtf8(""))
        self.tile_17.setObjectName(_fromUtf8("tile_17"))
        self.gridLayout_3.addWidget(self.tile_17, 10, 1, 1, 1)
        self.tile_19 = QtGui.QLineEdit(self.groupBox)
        self.tile_19.setToolTip(_fromUtf8(""))
        self.tile_19.setObjectName(_fromUtf8("tile_19"))
        self.gridLayout_3.addWidget(self.tile_19, 12, 1, 1, 1)
        self.generate = QtGui.QPushButton(self.groupBox)
        self.generate.setObjectName(_fromUtf8("generate"))
        self.gridLayout_3.addWidget(self.generate, 13, 0, 1, 3)
        self.lng = QtGui.QLineEdit(self.groupBox)
        self.lng.setObjectName(_fromUtf8("lng"))
        self.gridLayout_3.addWidget(self.lng, 2, 1, 1, 2)
        self.map_name = QtGui.QLineEdit(self.groupBox)
        self.map_name.setObjectName(_fromUtf8("map_name"))
        self.gridLayout_3.addWidget(self.map_name, 0, 1, 1, 2)
        self.label_18 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 12, 0, 1, 1)
        self.lat = QtGui.QLineEdit(self.groupBox)
        self.lat.setObjectName(_fromUtf8("lat"))
        self.gridLayout_3.addWidget(self.lat, 1, 1, 1, 2)
        self.tile_19_label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tile_19_label.setFont(font)
        self.tile_19_label.setText(_fromUtf8(""))
        self.tile_19_label.setObjectName(_fromUtf8("tile_19_label"))
        self.gridLayout_3.addWidget(self.tile_19_label, 12, 2, 1, 1)
        self.tile_17_label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tile_17_label.setFont(font)
        self.tile_17_label.setText(_fromUtf8(""))
        self.tile_17_label.setObjectName(_fromUtf8("tile_17_label"))
        self.gridLayout_3.addWidget(self.tile_17_label, 10, 2, 1, 1)
        self.tile_15 = QtGui.QLineEdit(self.groupBox)
        self.tile_15.setToolTip(_fromUtf8(""))
        self.tile_15.setObjectName(_fromUtf8("tile_15"))
        self.gridLayout_3.addWidget(self.tile_15, 8, 1, 1, 1)
        self.tile_15_label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tile_15_label.setFont(font)
        self.tile_15_label.setText(_fromUtf8(""))
        self.tile_15_label.setObjectName(_fromUtf8("tile_15_label"))
        self.gridLayout_3.addWidget(self.tile_15_label, 8, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 9, 0, 1, 1)
        self.tile_16 = QtGui.QLineEdit(self.groupBox)
        self.tile_16.setToolTip(_fromUtf8(""))
        self.tile_16.setObjectName(_fromUtf8("tile_16"))
        self.gridLayout_3.addWidget(self.tile_16, 9, 1, 1, 1)
        self.tile_size = QtGui.QSlider(self.groupBox)
        self.tile_size.setMinimum(200)
        self.tile_size.setMaximum(1500)
        self.tile_size.setSingleStep(50)
        self.tile_size.setPageStep(50)
        self.tile_size.setOrientation(QtCore.Qt.Horizontal)
        self.tile_size.setInvertedAppearance(False)
        self.tile_size.setInvertedControls(False)
        self.tile_size.setTickPosition(QtGui.QSlider.NoTicks)
        self.tile_size.setTickInterval(50)
        self.tile_size.setObjectName(_fromUtf8("tile_size"))
        self.gridLayout_3.addWidget(self.tile_size, 7, 1, 1, 1)
        self.tile_size_label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tile_size_label.setFont(font)
        self.tile_size_label.setObjectName(_fromUtf8("tile_size_label"))
        self.gridLayout_3.addWidget(self.tile_size_label, 7, 2, 1, 1)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 3, 0, 1, 3)
        self.formLayout.setWidget(10, QtGui.QFormLayout.SpanningRole, self.groupBox)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_11.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1247, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.cam1.setCurrentIndex(-1)
        self.cam2.setCurrentIndex(-1)
        self.cam3.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_10.setText(_translate("MainWindow", "Arm Visualization", None))
        self.label_9.setText(_translate("MainWindow", "Sensor Readings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main", None))
        self.label_5.setText(_translate("MainWindow", "Settings", None))
        self.label.setText(_translate("MainWindow", "Default Map", None))
        self.label_2.setText(_translate("MainWindow", "Cam Feed 1", None))
        self.label_3.setText(_translate("MainWindow", "Cam Feed 2", None))
        self.label_4.setText(_translate("MainWindow", "Cam Feed 3", None))
        self.groupBox.setTitle(_translate("MainWindow", "Map Generation", None))
        self.label_11.setText(_translate("MainWindow", "Tile Size:", None))
        self.label_8.setText(_translate("MainWindow", "Longitude:", None))
        self.label_7.setText(_translate("MainWindow", "Map Name:", None))
        self.label_6.setText(_translate("MainWindow", "Latitude:", None))
        self.label_12.setText(_translate("MainWindow", "API:", None))
        self.label_16.setText(_translate("MainWindow", "Tiles @ 15:", None))
        self.api_select.setItemText(0, _translate("MainWindow", "Bing", None))
        self.api_select.setItemText(1, _translate("MainWindow", "Google", None))
        self.tile_18.setText(_translate("MainWindow", "1", None))
        self.label_17.setText(_translate("MainWindow", "Tiles @ 18:", None))
        self.label_13.setText(_translate("MainWindow", "Tiles @ 17:", None))
        self.tile_17.setText(_translate("MainWindow", "1", None))
        self.tile_19.setText(_translate("MainWindow", "1", None))
        self.generate.setText(_translate("MainWindow", "Generate New Map", None))
        self.label_18.setText(_translate("MainWindow", "Tiles @ 19:", None))
        self.tile_15.setText(_translate("MainWindow", "1", None))
        self.label_15.setText(_translate("MainWindow", "Tiles @ 16:", None))
        self.tile_16.setText(_translate("MainWindow", "1", None))
        self.tile_size_label.setText(_translate("MainWindow", "200 px", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Setings", None))

